enum ActionType {
    // Accounting - Accounts
    REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS',
    RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS',
    SELECT_ACCOUNT = 'SELECT_ACCOUNT',

    // Accounting - Balance Sheet
    REQUEST_BALANCE_SHEET_REPORT_DATA = 'REQUEST_BALANCE_SHEET_REPORT_DATA',
    RECEIVE_BALANCE_SHEET_REPORT_DATA = 'RECEIVE_BALANCE_SHEET_REPORT_DATA',
    UPDATE_BALANCE_SHEET_REPORT_DATE_RANGE_START = 'UPDATE_BALANCE_SHEET_REPORT_DATE_RANGE_START',
    UPDATE_BALANCE_SHEET_REPORT_DATE_RANGE_END = 'UPDATE_BALANCE_SHEET_REPORT_DATE_RANGE_END',
    RESET_BALANCE_SHEET_REPORT_DATA = 'RESET_BALANCE_SHEET_REPORT_DATA',

    // Common - Data Export/Downloads
    REQUEST_EXPORT_DOWNLOAD = 'REQUEST_EXPORT_DOWNLOAD',
    RECEIVE_EXPORT_DOWNLOAD_ERROR = 'RECEIVE_EXPORT_DOWNLOAD_ERROR',
    RECEIVE_EXPORT_DOWNLOAD_INFO = 'RECEIVE_EXPORT_DOWNLOAD_INFO',
    RESET_EXPORT_STORE = 'RESET_EXPORT_STORE',

    // Accounting - Journal Entry
    REQUEST_JOURNAL_ENTRY = 'REQUEST_JOURNAL_ENTRY',
    RECEIVE_JOURNAL_ENTRY = 'RECEIVE_JOURNAL_ENTRY',
    REQUEST_SAVE_NEW_JOURNAL_ENTRY = 'REQUEST_SAVE_NEW_JOURNAL_ENTRY',
    NEW_JOURNAL_ENTRY_SAVE_COMPLETED = 'NEW_JOURNAL_ENTRY_SAVE_COMPLETED',
    REQUEST_SAVE_UPDATED_JOURNAL_ENTRY = 'REQUEST_SAVE_UPDATED_JOURNAL_ENTRY',
    UPDATED_JOURNAL_ENTRY_SAVE_COMPLETED = 'UPDATED_JOURNAL_ENTRY_SAVE_COMPLETED',
    REQUEST_POST_JOURNAL_ENTRY = 'REQUEST_POST_JOURNAL_ENTRY',
    POST_JOURNAL_ENTRY_COMPLETED = 'POST_JOURNAL_ENTRY_COMPLETED',
    REQUEST_DELETE_JOURNAL_ENTRY = 'REQUEST_DELETE_JOURNAL_ENTRY',
    DELETE_JOURNAL_ENTRY_COMPLETED = 'DELETE_JOURNAL_ENTRY_COMPLETED',
    INITIALIZE_NEW_JOURNAL_ENTRY = 'INITIALIZE_NEW_JOURNAL_ENTRY',
    EDIT_JOURNAL_ENTRY = 'EDIT_JOURNAL_ENTRY',
    UPDATE_JOURNAL_ENTRY_ENTRY_DATE = 'UPDATE_JOURNAL_ENTRY_ENTRY_DATE',
    UPDATE_JOURNAL_ENTRY_POST_DATE = 'UPDATE_JOURNAL_ENTRY_POST_DATE',
    UPDATE_JOURNAL_ENTRY_DESCRIPTION = 'UPDATE_JOURNAL_ENTRY_DESCRIPTION',
    UPDATE_JOURNAL_ENTRY_NOTE = 'UPDATE_JOURNAL_ENTRY_NOTE',
    UPDATE_JOURNAL_ENTRY_CHECK_NUMBER = 'UPDATE_JOURNAL_ENTRY_CHECK_NUMBER',
    ADD_JOURNAL_ENTRY_ACCOUNT = 'ADD_JOURNAL_ENTRY_ACCOUNT',
    REMOVE_JOURNAL_ENTRY_ACCOUNT = 'REMOVE_JOURNAL_ENTRY_ACCOUNT',
    UPDATE_JOURNAL_ENTRY_ACCOUNT_AMOUNT = 'UPDATE_JOURNAL_ENTRY_ACCOUNT_AMOUNT',
    RESET_DIRTY_JOURNAL_ENTRY = 'RESET_DIRTY_JOURNAL_ENTRY',
    RESET_JOURNAL_ENTRY_STORE_STATE = 'RESET_JOURNAL_ENTRY_STORE_STATE',

    // Accounting - Ledger
    REQUEST_LEDGER_REPORT_DATA = 'REQUEST_LEDGER_REPORT_DATA',
    RECEIVE_LEDGER_REPORT_DATA = 'RECEIVE_LEDGER_REPORT_DATA',
    UPDATE_LEDGER_REPORT_DATE_RANGE_START = 'UPDATE_LEDGER_REPORT_DATE_RANGE_START',
    UPDATE_LEDGER_REPORT_DATE_RANGE_END = 'UPDATE_LEDGER_REPORT_DATE_RANGE_END',
    RESET_LEDGER_REPORT_DATA = 'RESET_LEDGER_REPORT_DATA',

    // Common - Lookup Values
    REQUEST_LOOKUPS = 'REQUEST_LOOKUPS',
    RECEIVE_LOOKUPS = 'RECEIVE_LOOKUPS',

    // Accounting - Profit & Loss
    REQUEST_PROFIT_AND_LOSS_REPORT_DATA = 'REQUEST_PROFIT_AND_LOSS_REPORT_DATA',
    RECEIVE_PROFIT_AND_LOSS_REPORT_DATA = 'RECEIVE_PROFIT_AND_LOSS_REPORT_DATA',
    UPDATE_PROFIT_AND_LOSS_REPORT_DATE_RANGE_START = 'UPDATE_PROFIT_AND_LOSS_REPORT_DATE_RANGE_START',
    UPDATE_PROFIT_AND_LOSS_REPORT_DATE_RANGE_END = 'UPDATE_PROFIT_AND_LOSS_REPORT_DATE_RANGE_END',
    RESET_PROFIT_AND_LOSS_REPORT_DATA = 'RESET_PROFIT_AND_LOSS_REPORT_DATA',

    // Common - System Notifications
    SHOW_ALERT = 'SHOW_ALERT',
    DISMISS_ALERT = 'DISMISS_ALERT',

    // Common - Tenant
    REQUEST_TENANTS = 'REQUEST_TENANTS',
    RECEIVE_TENANTS = 'RECEIVE_TENANTS',
    SELECT_TENANT = 'SELECT_TENANT',
}

export default ActionType;